- pipeline: "Prod"
  on: "EVENT"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/main"
  priority: "NORMAL"
  fail_on_prepare_env_warning: true
  resources: "DEFAULT"
  actions:
  - action: "Upload files to main"
    type: "SFTP"
    input_type: "BUILD_ARTIFACTS"
    remote_path: "website"
    login: "techsoc"
    password: "secure!Fzpz2Ca6kQaEsXgjShpjDiNotYCgOM8t1oFFTiq8tvM=.zUPmM0OG2DFhgQ9jslIshA=="
    host: "165.227.231.194"
    authentication_mode: "PASS"
    deployment_excludes:
    - "node_modules/"
  - action: "[165.227.231.194] Execute npm install"
    type: "SSH_COMMAND"
    working_directory: "~/website"
    login: "techsoc"
    password: "secure!Fzpz2Ca6kQaEsXgjShpjDiNotYCgOM8t1oFFTiq8tvM=.zUPmM0OG2DFhgQ9jslIshA=="
    host: "165.227.231.194"
    authentication_mode: "PASS"
    commands:
    - "npm install"
    - ""
    run_as_script: true
    shell: "BASH"
  - action: "[165.227.231.194] Execute build and restart"
    type: "SSH_COMMAND"
    working_directory: "~/website"
    login: "techsoc"
    password: "secure!Fzpz2Ca6kQaEsXgjShpjDiNotYCgOM8t1oFFTiq8tvM=.zUPmM0OG2DFhgQ9jslIshA=="
    host: "165.227.231.194"
    authentication_mode: "PASS"
    commands:
    - "npm run build"
    - "pm2 restart TechsocWeb"
    - ""
    run_as_script: true
    shell: "BASH"
  - action: "Purge cache at bruneltech.net"
    type: "CLOUDFLARE"
    distribution_name: "bruneltech.net"
    purge_all: true
    zone_id: "6830f21d619b903a8b2e6e9950a682f4"
    integration_hash: "Og3KWYxk8mepBqRrbMyJNjQ9vG"
